### ISSUE TITLE
Mg potential missing

### ISSUE THREAD

**Issue by jan-janssen** [lfzhu-phys/Melting#1]
It seems like the Mg potential is missing: 
https://github.com/pyiron/pyiron_meltingpoint/tree/master/example_hcpMg

**Comment by lfzhu-phys** [comment]
For Mg, the potential is directly read from the pyiron potential database by

my_potential = "Mg.eam.fs"

**Comment by lfzhu-phys** [comment]
Yes, it seems not working on local pyiron environment. I will add the potential there.
